name = "olympiad-gkts"
compatibility_date = "2026-06-16"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist-cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "olympiad-gkts-db"
database_id = "4c30c9ab-0c53-4b8a-865a-7c9078d48c2f"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "LEARNING_FILES"
bucket_name = "olympiad-gkts-learning-files"

[vars]
STORAGE_BACKEND = "cloudflare"
LEARNING_ENABLED = "true"
